services:
  bot:
    build:
      context: services/bot
      dockerfile: Dockerfile
    container_name: my_python_app
    volumes:
      - ./services/bot:/app
    working_dir: /app
    ports:
      - "8080:8080"
    env_file:
      - .env
    tty: true
    stdin_open: true
    command: bash
  db:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
