services:
  python-app:
    build:
      context: services/bot
      dockerfile: Dockerfile
    container_name: my_python_app
    volumes:
      - ./services/bot:/app
    working_dir: /app
    ports:
      - "8080:8080"
    env_file:
      - .env
    tty: true
    stdin_open: true
    command: bash
