services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: speech-app
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - "${API_PORT}:8000"
    env_file:
      - ../secrets/speech-coach.env
    depends_on:
      - db
    tty: true
    stdin_open: true
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  db:
    image: postgres:latest
    container_name: speech-db
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
  minio:
    restart: always
    image: quay.io/minio/minio
    container_name: speech-minio
    ports:
      - "4566:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
volumes:
  db_data:
    driver: local
  minio_data:
    driver: local
