version: '3.8'

services:
  docusaurus:
    build: .
    container_name: docusaurus
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: "npm run start -- --host 0.0.0.0"
