global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
    metrics_path: '/metrics'

  - job_name: 'server'
    static_configs:
      - targets: ['server:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 4s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'server'

  - job_name: 'worker'
    static_configs:
      - targets: ['worker:8001']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 4s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'worker'
