"""add media table

Revision ID: 5ede0cf88364
Revises: 34f415198448
Create Date: 2025-04-09 15:10:55.540704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ede0cf88364'
down_revision: Union[str, None] = '34f415198448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_media_source', 'media', ['source_type', 'source_id'], unique=False)
    op.alter_column('question_tags', 'tag',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.add_column('questions', sa.Column('correct_answer', sa.Text(), nullable=True))
    op.alter_column('questions', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_index('idx_questions_category_active', 'questions', ['category', 'is_active'], unique=False)
    op.drop_column('questions', 'ideal_audio_url')
    op.drop_column('questions', 'ideal_answer')
    op.create_index('idx_user_answers_user_question', 'user_answers', ['user_id', 'question_id'], unique=False)
    op.drop_column('user_answers', 'answer_text')
    op.drop_column('user_answers', 'answer_audio_url')
    op.create_index('idx_user_question_history_assigned_at', 'user_question_history', ['assigned_at'], unique=False)
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index('idx_users_telegram_id', 'users', ['telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_telegram_id', table_name='users')
    op.alter_column('users', 'last_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index('idx_user_question_history_assigned_at', table_name='user_question_history')
    op.add_column('user_answers', sa.Column('answer_audio_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user_answers', sa.Column('answer_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index('idx_user_answers_user_question', table_name='user_answers')
    op.add_column('questions', sa.Column('ideal_answer', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('ideal_audio_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index('idx_questions_category_active', table_name='questions')
    op.alter_column('questions', 'category',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('questions', 'correct_answer')
    op.alter_column('question_tags', 'tag',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index('idx_media_source', table_name='media')
    op.drop_table('media')
    # ### end Alembic commands ###
