"""Add user quota table

Revision ID: 2e26869e48e8
Revises: 5ede0cf88364
Create Date: 2025-04-09 17:13:16.037713

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2e26869e48e8"
down_revision: Union[str, None] = "5ede0cf88364"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_quotas",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("total_allowed", sa.Integer(), nullable=True),
        sa.Column("used", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_quotas")
    # ### end Alembic commands ###
