"""Rename user name column

Revision ID: b6c45aa427db
Revises: 2e26869e48e8
Create Date: 2025-04-09 17:42:21.154121

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b6c45aa427db"
down_revision: Union[str, None] = "2e26869e48e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("user_name", sa.String(length=255), nullable=True))
    op.drop_column("users", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "username", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("users", "user_name")
    # ### end Alembic commands ###
