---
- name: Deploy FastAPI app
  hosts: fastapi
  become: true
  roles:
    - fastapi

- name: Deploy PostgreSQL
  hosts: postgresql
  become: true
  roles:
    - postgresql

# - name: Deploy MinIO
#   hosts: minio
#   become: true
#   roles:
#     - minio
