name: CI

on:
  push:
    branches: [main]
    paths:
      - 'src/app/**.py'
      - '.pre-commit-config.yaml'
      - 'tests/**.py'
  pull_request:
    branches: [main]
    paths:
      - 'src/app/**.py'
      - '.pre-commit-config.yaml'
      - 'tests/**.py'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/server/requirements.txt
          pip install -r requirements.dev.txt
          pip install pytest pytest-asyncio pytest-cov

      - name: Run tests
        run: |
          python -m pytest tests/src/shared/ -v --cov=src/shared --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
